services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus/tmp:/prometheus
      - ./env/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - ./env/grafana/tmp:/var/lib/grafana
      - ./env/grafana/grafana.ini:/etc/grafana/grafana.ini

  db:
    image: postgres
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=watch_price
    ports:
      - "5432:5432"

  app:
    image: 'application:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/watch_price
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    ports:
      - "8080:8080"
