create table IF NOT EXISTS watch (
    id bigint generated by default as identity,
    watch_id varchar(255) not null ,
    watch_name varchar(255) not null ,
    unit_price bigint not null ,
    discount_on_quantity integer,
    discounted_price bigint, primary key (id)
);